CREATE TABLESPACE user_ts 
    DATAFILE 'c:\oracle\oradata\ora\userts.dbf' SIZE 10M
    AUTOEXTEND ON NEXT 200K  MAXSIZE 500M;

CREATE USER penny IDENTIFIED BY password;

GRANT create session TO penny;
GRANT create table TO penny;
GRANT create view TO penny;
GRANT create any trigger TO penny;
GRANT create any procedure TO penny;
GRANT create sequence TO penny;
GRANT create synonym TO penny;
  
ALTER USER penny QUOTA 500M ON user_ts;

ALTER SESSION SET CURRENT_SCHEMA = penny;

CREATE TABLE users
(
username VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
enabled  NUMBER(1) DEFAULT 1 NOT NULL,
PRIMARY KEY (username)
) TABLESPACE user_ts;

CREATE TABLE user_roles
(
user_role_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
username     VARCHAR(45) NOT NULL,
role         VARCHAR(45) NOT NULL,
CONSTRAINT pk_user_role_id PRIMARY KEY (user_role_id),
CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)
) TABLESPACE user_ts;